import * as stylex from "@stylexjs/stylex";
import {
  colors,
  space,
  type,
  radii,
  shadows,
  timing,
  controls,
} from "./tokens.stylex";
const mobile = "@media (max-width: 700px)";
export const styles = stylex.create({
  control: {
    height: controls.height,
    minHeight: controls.height,
    borderRadius: controls.radius,
    fontSize: controls.text,
    fontWeight: 450,
    lineHeight: "1",
    paddingBlock: 0,
    paddingInline: 12,
    gap: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#ffffff90",
    backdropFilter: "blur(14px)",
    boxShadow: "inset 0 1px 0 #ffffff99, 0 1px 3px #00000006",
    backgroundColor: {
      default: "#ffffff70",
      ":hover": controls.hover,
      ":active": controls.pressed,
    },
    color: colors.text,
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: 2,
    outlineColor: controls.focus,
    outlineOffset: 2,
    transitionProperty: "background-color, color, box-shadow, translate",
    transitionDuration: timing.fast,
  },
  controlAccent: {
    backgroundColor: {
      default: "#242424e8",
      ":hover": "#414141",
      ":active": "#111",
    },
    color: colors.onSolid,
    borderColor: "#ffffff20",
    boxShadow: "inset 0 1px 0 #ffffff18, 0 1px 4px #00000010",
  },
  controlIcon: { width: controls.height, paddingInline: 0, flexShrink: 0 },

  pageResults: {
    display: "grid",
    gridTemplateColumns: "repeat(4,minmax(0,1fr))",
    gap: 12,
    maxHeight: 260,
    overflowY: "auto",
    marginTop: 16,
  },
  pageResult: {
    height: 135,
    padding: 8,
    backgroundColor: colors.hover,
    borderRadius: 4,
  },
  pageResultImage: { width: "100%", height: "100%", objectFit: "contain" },
  splash: {
    position: "fixed",
    inset: 0,
    zIndex: 100,
    backgroundColor: colors.canvas,
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
  },
  splashInner: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 24,
    transform: "translateY(-12px)",
  },
  splashBrand: {
    fontSize: 36,
    fontWeight: 550,
    letterSpacing: "-2px",
    lineHeight: 1,
  },
  splashCaption: { fontSize: 11, color: colors.muted, letterSpacing: ".02em" },
  splashCover: {
    width: 110,
    height: 150,
    objectFit: "contain",
    filter: "drop-shadow(0 6px 14px #00000012)",
  },
  splashTrack: {
    width: 64,
    height: 1,
    backgroundColor: colors.border,
    overflow: "hidden",
    display: "block",
  },
  splashProgress: {
    width: 30,
    height: 1,
    backgroundColor: colors.text,
    display: "block",
  },

  masthead: {
    position: "fixed",
    top: 18,
    left: { default: 28, [mobile]: 12 },
    right: { default: 28, [mobile]: 12 },
    height: 46,
    zIndex: 8,
    display: "flex",
    alignItems: "center",
    pointerEvents: "none",
  },
  wordmark: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: { default: type.brand, [mobile]: "21px" },
    fontWeight: 550,
    letterSpacing: "-1px",
    lineHeight: 1,
    color: colors.text,
    textDecoration: "none",
    padding: space.xs,
    pointerEvents: "auto",
  },
  symbol: { width: 22, height: 22 },
  nav: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: space.md,
    pointerEvents: "auto",
  },
  aboutButton: {
    fontSize: 0,
    width: 32,
    height: 34,
    display: { default: "inline-flex", [mobile]: "none" },
  },
  solidButton: {
    height: 40,
    borderRadius: radii.pill,
    backgroundColor: colors.solid,
    color: colors.onSolid,
    paddingInline: space.md,
    fontSize: type.small,
  },
  savedCount: {
    fontSize: type.micro,
    color: colors.subtle,
    paddingLeft: 10,
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: "#555",
  },
  searchTrigger: {
    position: "absolute",
    left: "50%",
    transform: "translateX(-50%)",
    height: { default: 46, [mobile]: 40 },
    width: { default: 350, [mobile]: 40 },
    justifyContent: "flex-start",
    paddingInline: { default: 17, [mobile]: 11 },
    gap: space.sm,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.floating,
    boxShadow: "0 2px 5px #00000004",
    fontSize: type.body,
    color: colors.muted,
    pointerEvents: "auto",
  },
  searchText: {
    display: { default: "inline", [mobile]: "none" },
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shortcut: {
    display: { default: "inline", [mobile]: "none" },
    marginLeft: "auto",
    fontFamily: type.family,
    color: colors.subtle,
    fontSize: type.body,
    whiteSpace: "nowrap",
  },
  gallery: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    cursor: "grab",
    touchAction: "none",
    backgroundColor: colors.canvas,
  },
  webgl: { position: "absolute", inset: 0, zIndex: 1, pointerEvents: "none" },
  cards: { position: "absolute", inset: 0, zIndex: 2, pointerEvents: "none" },
  artifact: {
    position: "absolute",
    top: 0,
    left: 0,
    display: "block",
    padding: 0,
    pointerEvents: "auto",
    textAlign: "left",
    cursor: "inherit",
    transformOrigin: "center",
  },
  paper: {
    position: "absolute",
    inset: 0,
    display: "block",
    outline: "1px solid #00000006",
    boxShadow: { default: shadows.paper, ":hover": shadows.paperHover },
    transitionProperty: "box-shadow",
    transitionDuration: timing.normal,
  },
  artifactImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    display: "block",
  },
  failed: {
    backgroundColor: "#f5f5f5",
    padding: space.md,
    display: "flex",
    alignItems: "center",
    fontSize: 20,
  },
  grid: {
    position: "absolute",
    inset: 0,
    overflow: "auto",
    paddingTop: 100,
    paddingBottom: 140,
    paddingInline: { default: 60, [mobile]: 24 },
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(5,minmax(0,1fr))",
      "@media (max-width:1100px)": "repeat(4,minmax(0,1fr))",
      [mobile]: "repeat(2,minmax(0,1fr))",
    },
    gap: { default: "45px 55px", [mobile]: "32px 25px" },
    alignItems: "start",
    backgroundColor: colors.canvas,
  },
  gridCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    padding: 0,
    textAlign: "left",
  },
  gridImage: {
    width: "100%",
    height: { default: 240, [mobile]: 215 },
    objectFit: "contain",
    filter: "drop-shadow(2px 5px 5px #28282010)",
  },
  loadMore: { gridColumn: "1 / -1", justifySelf: "center" },
  dock: {
    position: "fixed",
    zIndex: 10,
    bottom: { default: 30, [mobile]: 23 },
    left: "50%",
    transform: "translateX(-50%)",
    height: 56,
    display: "flex",
    alignItems: "center",
    padding: "6px 9px",
    gap: space.sm,
    backgroundColor: colors.floating,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    boxShadow: shadows.dock,
    borderRadius: radii.pill,
    maxWidth: "calc(100vw - 24px)",
    backdropFilter: "blur(16px)",
  },
  switch: { display: "flex", alignItems: "center", gap: 3 },
  switchButton: {
    height: 36,
    paddingInline: { default: 12, [mobile]: 9 },
    fontSize: type.small,
    borderRadius: radii.pill,
    whiteSpace: "nowrap",
  },
  selected: {
    backgroundColor: controls.hover,
    color: colors.text,
    fontWeight: 550,
  },
  segmentButton: {
    width: { default: 100, [mobile]: 68 },
    backgroundColor: {
      default: "transparent",
      ":hover": "transparent",
      ":active": "transparent",
    },
    backgroundImage: "none",
    backdropFilter: "none",
    borderColor: "transparent",
    boxShadow: "none",
    fontWeight: 450,
    fontSize: { default: 12, [mobile]: 11 },
    paddingInline: { default: 8, [mobile]: 4 },
    position: "relative",
    zIndex: 1,
    justifyContent: "center",
    outlineOffset: -3,
  },
  compactNavigation: {
    width: { default: 40, [mobile]: 26 },
    minWidth: { default: 40, [mobile]: 26 },
  },
  dockSelection: {
    position: "absolute",
    left: 0,
    top: 0,
    height: controls.height,
    borderRadius: controls.radius,
    backgroundColor: controls.selection,
    pointerEvents: "none",
    transitionProperty: "transform",
    transitionDuration: "420ms",
    transitionTimingFunction: "cubic-bezier(.22,1,.36,1)",
  },
  dockLine: { height: 19, width: 1, backgroundColor: colors.border },
  zoom: {
    display: { default: "flex", [mobile]: "none" },
    alignItems: "center",
  },
  zoomButton: { width: 30, height: 36, fontSize: type.micro },
  zoomValue: {
    minWidth: 46,
    fontVariantNumeric: "tabular-nums",
    color: colors.muted,
  },
  empty: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%,-10%)",
    textAlign: "center",
    zIndex: 4,
    width: { default: "auto", [mobile]: "85%" },
  },
  emptyTitle: { fontSize: 32, letterSpacing: "-1px" },
  muted: { fontSize: type.body, color: colors.muted, lineHeight: type.line },
  primary: {
    display: "inline-flex",
    gap: space.sm,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.solid,
    color: colors.onSolid,
    padding: "13px 18px",
    borderRadius: radii.pill,
    fontSize: type.body,
    textDecoration: "none",
  },
  searchDialog: {
    width: 610,
    top: "15vh",
    marginTop: 0,
    borderRadius: radii.panel,
  },
  searchLine: {
    display: "flex",
    alignItems: "center",
    gap: 15,
    padding: { default: "20px 25px", [mobile]: 16 },
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  searchInput: {
    borderWidth: 0,
    backgroundColor: "transparent",
    minWidth: 0,
    flex: 1,
    fontSize: { default: 18, [mobile]: 15 },
    color: colors.text,
    outlineWidth: 0,
  },
  iconButton: {
    height: 38,
    width: 38,
    borderRadius: radii.pill,
    padding: 9,
    backgroundColor: { default: "transparent", ":hover": colors.hover },
  },
  searchBody: { padding: { default: 30, [mobile]: 24 } },
  eyebrow: {
    fontSize: type.micro,
    fontWeight: 550,
    letterSpacing: "1.5px",
    display: "flex",
    alignItems: "center",
    gap: space.xs,
  },
  suggestions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 9,
    marginBlock: "20px 30px",
  },
  suggestion: {
    padding: "10px 13px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.pill,
    fontSize: type.body,
  },
  searchDone: { display: "flex", marginTop: 18, marginLeft: "auto" },
  filterbar: {
    display: "flex",
    alignItems: "center",
    gap: 15,
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  filterLeft: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "12px 18px",
  },
  resultCount: { fontSize: type.small, fontVariantNumeric: "tabular-nums" },
  selectWrap: { position: "relative", display: "flex", alignItems: "center" },
  select: {
    fontSize: type.small,
    appearance: "none",
    padding: "10px 22px 10px 0",
    borderWidth: 0,
    color: colors.muted,
    backgroundColor: "transparent",
    cursor: "pointer",
    maxWidth: 155,
  },
  selectIcon: {
    position: "absolute",
    right: 0,
    width: 12,
    height: 12,
    pointerEvents: "none",
  },
  clear: { fontSize: type.small, gap: 3 },
  aboutDialog: { width: 650, padding: { default: 55, [mobile]: "45px 28px" } },
  close: { position: "absolute", top: 16, right: 16 },
  aboutTitle: {
    fontSize: { default: 40, [mobile]: 32 },
    fontWeight: 400,
    lineHeight: 1.15,
    letterSpacing: "-1.3px",
    marginBlock: 25,
  },
  aboutText: { fontSize: 14, lineHeight: 1.8, color: colors.muted },
  stats: {
    display: "flex",
    gap: 40,
    paddingBlock: 24,
    borderBlockWidth: 1,
    borderBlockStyle: "solid",
    borderBlockColor: colors.border,
    marginBlock: 30,
  },
  stat: {
    display: "flex",
    flexDirection: "column",
    fontSize: 10,
    gap: 5,
    color: colors.muted,
  },
  statValue: { fontSize: 28, fontWeight: 400, color: colors.text },
  sourceNote: { fontSize: 10, lineHeight: 1.8, color: colors.muted },
  reader: {
    position: "fixed",
    inset: 0,
    maxWidth: "none",
    width: "100%",
    height: "100%",
    maxHeight: "none",
    borderRadius: 0,
    margin: 0,
    overflow: "hidden",
  },
  readerHeader: {
    position: "absolute",
    inset: "0 0 auto",
    height: { default: 68, [mobile]: 60 },
    zIndex: 10,
    paddingInline: { default: 28, [mobile]: 15 },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    backgroundImage: "linear-gradient(#fff 65%,#ffffff00)",
  },
  readerBack: { fontSize: type.small, height: 40 },
  detailsButton: {
    marginLeft: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.pill,
    width: 36,
    height: 36,
  },
  readerBody: {
    display: "flex",
    height: "100%",
    paddingTop: { default: 68, [mobile]: 60 },
  },
  info: {
    display: "none",
    position: "absolute",
    zIndex: 12,
    top: 65,
    right: 24,
    width: 300,
    maxHeight: "calc(100% - 155px)",
    height: "auto",
    backgroundColor: colors.canvas,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.panel,
    boxShadow: shadows.dock,
    padding: 24,
    overflowY: "auto",
  },
  infoOpen: { display: "block" },
  reportTitle: {
    fontSize: 28,
    lineHeight: 1.12,
    fontWeight: 400,
    letterSpacing: "-.8px",
    marginBlock: "18px 13px",
  },
  industry: {
    fontSize: 9,
    display: "inline-block",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.small,
    color: colors.muted,
    padding: "5px 8px",
  },
  reportCover: { marginBlock: "27px 21px" },
  reportImage: {
    display: "block",
    width: "auto",
    maxWidth: "100%",
    maxHeight: 190,
    boxShadow: shadows.paper,
  },
  description: { fontSize: type.small, lineHeight: 1.8, color: colors.muted },
  infoPair: { display: "flex", flexDirection: "column", gap: 7, marginTop: 24 },
  infoKey: { fontSize: 8, letterSpacing: "1.5px", color: colors.subtle },
  infoValue: { fontWeight: 400, fontSize: type.small, lineHeight: 1.5 },
  sourceLink: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBlock: 23,
    fontSize: 10,
    textUnderlineOffset: 4,
    lineHeight: 1.7,
  },
  availability: {
    fontSize: 10,
    lineHeight: 1.7,
    color: colors.muted,
    paddingTop: 17,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
  },
  stage: {
    position: "relative",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    backgroundColor: colors.canvas,
  },
  pageCanvas: {
    position: "absolute",
    inset: 0,
    touchAction: "none",
    cursor: "grab",
    backgroundColor: colors.canvas,
  },
  readerDock: {
    position: "absolute",
    zIndex: 8,
    bottom: 26,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: { default: 12, [mobile]: 6 },
    backgroundColor: colors.floating,
    padding: { default: "6px 9px", [mobile]: "6px 6px" },
    borderRadius: radii.pill,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    boxShadow: shadows.dock,
    whiteSpace: "nowrap",
    maxWidth: "calc(100% - 20px)",
  },
  pageNavigation: {
    display: "flex",
    gap: { default: 4, [mobile]: 2 },
    alignItems: "center",
  },
  navButton: { height: 36, width: 34, fontSize: type.small },
  pageNumber: {
    width: { default: 54, [mobile]: 38 },
    fontSize: 10,
    fontVariantNumeric: "tabular-nums",
    minWidth: { default: 54, [mobile]: 38 },
    textAlign: "center",
    color: colors.muted,
  },
  status: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: "40px 30px 110px",
  },
  statusTitle: { fontSize: 13, fontWeight: 400, marginBlock: "25px 8px" },
  unavailable: { maxHeight: "38vh", maxWidth: 230, boxShadow: shadows.paper },
  toast: {
    position: "fixed",
    zIndex: 100,
    bottom: 105,
    left: "50%",
    transform: "translate(-50%,8px)",
    padding: "12px 18px",
    backgroundColor: colors.solid,
    color: colors.onSolid,
    fontSize: type.body,
    borderRadius: radii.pill,
    opacity: 0,
    pointerEvents: "none",
    transitionProperty: "opacity,transform",
    transitionDuration: timing.fast,
    whiteSpace: "nowrap",
  },
  toastVisible: { opacity: 1, transform: "translate(-50%,0)" },
  transitionCover: {
    position: "fixed",
    zIndex: 9,
    objectFit: "contain",
    transformOrigin: "top left",
    pointerEvents: "none",
  },
  layoutCover: {
    position: "fixed",
    zIndex: 6,
    pointerEvents: "none",
    objectFit: "contain",
    transformOrigin: "top left",
  },
});
export type Slot = keyof typeof styles;
const controlSlots = new Set<Slot>([
  "solidButton",
  "primary",
  "switchButton",
  "zoomButton",
  "navButton",
  "iconButton",
  "readerBack",
  "detailsButton",
  "aboutButton",
  "suggestion",
  "clear",
  "searchTrigger",
]);
const iconSlots = new Set<Slot>([
  "zoomButton",
  "navButton",
  "iconButton",
  "detailsButton",
  "aboutButton",
]);
function controlStyles(slots: Slot[]): Slot[] {
  const result = [...slots];
  if (slots.some((s) => controlSlots.has(s))) {
    result.push("control");
    if (slots.some((s) => iconSlots.has(s))) result.push("controlIcon");
    if (slots.includes("solidButton") || slots.includes("primary"))
      result.push("controlAccent");
    if (slots.includes("selected")) result.push("selected");
  }
  if (slots.includes("navButton")) result.push("compactNavigation");
  if (slots.includes("pageNumber")) result.push("pageNumber");
  if (slots.includes("segmentButton")) result.push("segmentButton");
  return result;
}
export function cx(slot: Slot, ...variants: Slot[]): string {
  return (
    (controlSlots.has(slot) ? "glass-control " : "") +
    (stylex.props(...controlStyles([slot, ...variants]).map((s) => styles[s]))
      .className || "")
  );
}

/** Applies compiled StyleX slots to controller-created DOM as well as Astro markup. */
const bindings: [string, Slot][] = [
  [".masthead", "masthead"],
  [".wordmark", "wordmark"],
  [".archive-symbol", "symbol"],
  [".masthead nav", "nav"],
  ["#about", "aboutButton"],
  ["#saved,#save-report", "solidButton"],
  ["#saved-count", "savedCount"],
  ["#open-search", "searchTrigger"],
  ["#open-search span", "searchText"],
  ["kbd", "shortcut"],
  [".gallery", "gallery"],
  [".webgl", "webgl"],
  [".canvas-cards", "cards"],
  [".artifact", "artifact"],
  [".artifact-paper", "paper"],
  [".artifact img", "artifactImage"],
  [".image-failed", "failed"],
  [".grid-view", "grid"],
  [".grid-card", "gridCard"],
  [".grid-card img", "gridImage"],
  [".load-more", "loadMore"],
  [".dock", "dock"],
  [".view-switch", "switch"],
  [".view-switch button", "switchButton"],
  [".view-switch button", "segmentButton"],
  [".dock-line", "dockLine"],
  [".zoom-controls", "zoom"],
  [".zoom-controls button", "zoomButton"],
  ["#zoom-value", "zoomValue"],
  [".empty", "empty"],
  [".empty>span", "emptyTitle"],
  [".empty p,#search-count,.report-status p,.page-error p", "muted"],
  [".primary", "primary"],
  [".search-dialog", "searchDialog"],
  [".search-line", "searchLine"],
  ["#search-input", "searchInput"],
  [".icon-button", "iconButton"],
  [".search-body", "searchBody"],
  [".eyebrow", "eyebrow"],
  [".suggestions", "suggestions"],
  [".suggestions button", "suggestion"],
  ["#search-done", "searchDone"],
  [".filterbar", "filterbar"],
  [".filter-left", "filterLeft"],
  ["#result-count", "resultCount"],
  [".select-wrap", "selectWrap"],
  [".select-wrap select", "select"],
  [".select-wrap svg", "selectIcon"],
  [".clear", "clear"],
  [".about-dialog", "aboutDialog"],
  [".dialog-close", "close"],
  [".about-dialog h2", "aboutTitle"],
  [".about-dialog p", "aboutText"],
  [".about-stats", "stats"],
  [".about-stats>span", "stat"],
  [".about-stats strong", "statValue"],
  [".source-note", "sourceNote"],
  [".reader", "reader"],
  [".reader-header", "readerHeader"],
  ["#close-reader", "readerBack"],
  ["#report-details", "detailsButton"],
  [".reader-body", "readerBody"],
  [".report-info", "info"],
  [".report-info h2", "reportTitle"],
  [".report-industry", "industry"],
  [".report-cover", "reportCover"],
  [".report-cover img", "reportImage"],
  [".report-description", "description"],
  [".info-pair", "infoPair"],
  [".info-pair>span", "infoKey"],
  [".info-pair strong", "infoValue"],
  [".source-link", "sourceLink"],
  [".availability", "availability"],
  [".report-stage", "stage"],
  [".page-canvas", "pageCanvas"],
  [".reader-dock", "readerDock"],
  ["#page-navigation,#page-zoom", "pageNavigation"],
  ["#page-navigation button,#page-zoom button", "navButton"],
  ["#page-number,#page-reset", "pageNumber"],
  [".report-status", "status"],
  [".report-status h3,.page-error h3", "statusTitle"],
  [".unavailable-cover", "unavailable"],
  [".toast", "toast"],
  [".transition-cover", "transitionCover"],
  [".layout-cover", "layoutCover"],
];
const applied = new WeakMap<Element, string[]>();
export function syncStyles(root: ParentNode = document): void {
  const groups = new Map<Element, Slot[]>();
  for (const [selector, slot] of bindings)
    for (const el of root.querySelectorAll(selector)) {
      const slots = groups.get(el) || [];
      slots.push(slot);
      groups.set(el, slots);
    }
  for (const [el, slots] of groups) {
    if (el.classList.contains("selected")) slots.push("selected");
    if (el.classList.contains("toast") && el.classList.contains("show"))
      slots.push("toastVisible");
    if (el.classList.contains("report-info") && el.closest(".details-open"))
      slots.push("infoOpen");
    if (slots.some((slot) => controlSlots.has(slot)))
      el.classList.add("glass-control");
    const previous = applied.get(el) || [];
    const next = (
      stylex.props(...controlStyles(slots).map((s) => styles[s])).className ||
      ""
    )
      .split(" ")
      .filter(Boolean);
    el.classList.remove(...previous);
    el.classList.add(...next);
    applied.set(el, next);
  }
}
